import ButtonComponen from "@/components/button/button"
import styles from '@/app/page.module.css'

export const metadata = {
    title: 'This Login On Continue Admin',
    description: 'Generated by create next app',
}

export default function Home()
{
    return (
        <main className={styles.main}>
            <div><ButtonComponen/></div>
        </main>
    )
}