import ButtonComponen from "@/components/button/button"
import styles from '@/app/page.module.css'

export const metadata = {
    title: 'Show Menu',
    description: 'Generated by create next app',
}

export default function Home()
{
    return (
        <main className={styles.main}>
            <div>Menu</div>
        </main>
    )
}